# This is a basic workflow to help you get started with Actions

name: Converge All Nodes 

on:
  push:
    branches: 
      - main
    paths:
      - 'policyfiles/**'
  workflow_dispatch:
  
jobs:
  Setup-ChefWorkstation:
    runs-on: self-hosted
    steps:
      - name: Chef Installed?
        continue-on-error: true
        id: check-chef
        run: chef -v
        
      - name: Install ChefWorkstation v21.2.278
        if: steps.check-chef.outcome == 'failure'
        run: |
          wget https://packages.chef.io/files/stable/chef-workstation/21.2.278/el/8/chef-workstation-21.2.278-1.el7.x86_64.rpm
          sudo rpm -ivh chef-workstation-21.2.278-1.el7.x86_64.rpm
          rm chef-workstation-21.2.278-1.el7.x86_64.rpm
          chef -v

  Push-Policyfiles-to-ChefServer:
    runs-on: self-hosted
    needs: Setup-ChefWorkstation
    steps:
      - uses: actions/checkout@v2
      - name: Create/push Policyfile.lock
        run: |
          chef update policyfiles/db-server.rb -c .chef/config.rb
          chef update policyfiles/web-server.rb -c .chef/config.rb
          chef push staging policyfiles/db-server.rb -c .chef/config.rb
          chef push staging policyfiles/web-server.rb -c .chef/config.rb
  
  Converge-Nodes:
    runs-on: self-hosted
    needs: Push-Policyfiles-to-ChefServer
    environment:
      name: staging
    steps:
      - name: Create/push Policyfile.lock
        run: 
          knife ssh 'policy_group:staging' 'sudo chef-client' -c .chef/config.rb
          
  Inspec-Test:
    runs-on: self-hosted
    needs: Converge-Nodes
    continue-on-error: true
    steps:
      - name: Run Inspec (DB servers)
        id: inspec-check-1
        run: for i in `knife search 'policy_group:staging AND policy_name:db-server' -i -c .chef/config.rb | sort`; do inspec exec test/setup_postgresql_test.rb --target ssh://r-goto@$i -i ~/.ssh/nodes_shared
          
      - name: Run Inspec (WEB servers)
        id: inspec-check-2
        if: steps.inspec-check-1.outcome == 'success'
        run: for i in `knife search 'policy_group:staging AND policy_name:web-server' -i -c .chef/config.rb | sort`; do inspec exec test/setup_nginx_test.rb --target ssh://r-goto@$i -i ~/.ssh/nodes_shared

  Roll-Back:
    runs-on: self-hosted
    needs: Converge-Nodes
    
