# This is a basic workflow to help you get started with Actions

name: Converge

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  Setup_ChefWorkstation:
    runs-on: self-hosted
    steps:
      - name: Check ChefWorkstation v21.2.278
        run: chef -v
      
  Push_New_Policyfile:
    runs-on: self-hosted
    needs: Setup_ChefWorkstation
    steps:
      - uses: actions/checkout@v2
      - name: Create/push Policyfile.lock
        run: |
          chef update db-server.rb
          chef update web-server.rb
          chef push staging db-server.rb
          chef push staging web-server.rb
  
  Converge_nodes:
    runs-on: self-hosted
    needs: Push_New_Policyfile
    steps:
      - name: Create/push Policyfile.lock
        run: 
          knife ssh 'policy_group:staging' 'sudo chef-client'
