# This is a basic workflow to help you get started with Actions

name: Converge All Nodes 

on:
  push:
    branches: 
      - main
    paths:
      - 'policyfiles/**'
  workflow_dispatch:
  
jobs:
  Setup-ChefWorkstation:
    runs-on: self-hosted
    steps:
      - name: Checking if installation required
        continue-on-error: true
        id: check
        run: sudo dpkg -l | grep chef
      - name: Installing ChefWorkstation v21.2.278
        if: steps.check.outcome == 'failure'
        run: |
          wget -q https://packages.chef.io/files/stable/chef-workstation/21.2.278/ubuntu/20.04/chef-workstation_21.2.278-1_amd64.deb
          sudo dpkg -i chef-workstation_21.2.278-1_amd64.deb
          chef -v

  Push-Policyfiles-to-ChefServer:
    runs-on: self-hosted
    needs: Setup-ChefWorkstation
    steps:
      - uses: actions/checkout@v2
      - name: Create/push Policyfile.lock
        run: |
          chef update policyfiles/db-server.rb -c $GITHUB_WORKSPACE/.chef/config.rb
          chef update policyfiles/web-server.rb -c $GITHUB_WORKSPACE/.chef/config.rb
          chef push staging policyfiles/db-server.rb -c $GITHUB_WORKSPACE/.chef/config.rb
          chef push staging policyfiles/web-server.rb -c $GITHUB_WORKSPACE/.chef/config.rb
  
  Converge-Nodes:
    runs-on: self-hosted
    needs: Push-Policyfiles-to-ChefServer
    steps:
      - name: Create/push Policyfile.lock
        run: 
          knife ssh 'policy_group:staging' 'sudo chef-client' -c $GITHUB_WORKSPACE/.chef/config.rb
  Test:
    runs-on: self-hosted
    needs: Converge-Nodes
    steps:
      - name: Run Inspec
        continue-on-error: true
        run: |
          for i in `knife search 'policy_group:staging AND policy_name:web-server' -i -c $GITHUB_WORKSPACE/.chef/config.rb | sort`; do inspec exec $GITHUB_WORKSPACE/test/setup_nginx_test.rb --target ssh://r-goto@$i -i ~/.ssh/nodes_shared || echo 'Inspec failure!'; done
          for i in `knife search 'policy_group:staging AND policy_name:db-server' -i -c $GITHUB_WORKSPACE/.chef/config.rb | sort`; do inspec exec $GITHUB_WORKSPACE/test/setup_postgresql_test.rb --target ssh://r-goto@$i -i ~/.ssh/nodes_shared || echo 'Inspec failure!'; done
